FROM node:alpine as build

# Specify working directory (for linux)
WORKDIR /usr/app

# Add '/app/node_modules/.bin' to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

# Install dependencies
COPY package*.json /usr/app/
RUN npm install --silent

# Copy react app to the container
COPY ./ /usr/app/

# Build app (packages app in /usr/app/build folder)
RUN npm run build

# Copy build files to nginx staging(?)
FROM nginx:alpine
COPY --from=build /usr/app/build/ /usr/share/nginx/html

# If updating nginx config
#RUN rm /etc/nginx/nginx.conf
#COPY nginx.conf /etc/nginx/conf.d

# Start nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
